// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-cQCnYd-D5ceOruXzLag63ozAjdLXg2w',
    appId: '1:871961943336:web:f0879b5c02fa07c2cb441d',
    messagingSenderId: '871961943336',
    projectId: 'rummi-poker',
    authDomain: 'rummi-poker.firebaseapp.com',
    storageBucket: 'rummi-poker.firebasestorage.app',
    measurementId: 'G-TFKN3REZQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuwL9RffG0wuE3QCXSovVCguV819DcJ9M',
    appId: '1:871961943336:android:a558a876accfe695cb441d',
    messagingSenderId: '871961943336',
    projectId: 'rummi-poker',
    storageBucket: 'rummi-poker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyIU0ARQxh2ggizAwTT79UB0TdM8xyVh8',
    appId: '1:871961943336:ios:ee247f57e68563d5cb441d',
    messagingSenderId: '871961943336',
    projectId: 'rummi-poker',
    storageBucket: 'rummi-poker.firebasestorage.app',
    iosBundleId: 'com.cheng80.rummipoker',
  );
}
